platform_homepage:
    path:     /
    defaults: { _controller: PlatformBundle:Default:index }

hello_the_world:
    path:     /hello-world
    defaults: { _controller: PlatformBundle:Advert:index }


about_page:
    path:     /about
    defaults: { _controller: PlatformBundle:About:index }